services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/hermes_prod
      - SECRET_KEY_BASE=8Al871gEojfiqv4zHTMOQnJO93b5YW2LUD9lRoM7fpNKULAq7Wfv50T+8lA5NoLm
      - PORT=4000
      - PHX_HOST=localhost
    restart: always
    command: bin/hermes start
    container_name: hermes_app  # Add a specific container name

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hermes_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: hermes_db  # Add a specific container name

volumes:
  postgres_data:
